### ISSUE TITLE
yükleyemiyorum requirements.txt hatası

### ISSUE THREAD

**Issue by fdemir25** [Vitaee/PythonileSesliAsistanV3#2]
Merhaba, öncelikle programa baya ilgi gösterdim ama çalıştırmayı başaramadım. Şöyle bi hata alıyorum. yardımcı olabilir misiniz.
![Adsız](https://user-images.githubusercontent.com/60274884/95755861-9abec080-0cad-11eb-8f69-be5e70e0d705.png)

**Comment by fdemir25** [comment]
requirements.txt dosyasındaki modülleri teker teker yükleyemiyorum
her yolu denedim ama olmadı.
![123](https://user-images.githubusercontent.com/60274884/95758083-a52e8980-0cb0-11eb-91c9-7674358da782.png)

**Comment by Vitaee** [comment]
Merhabalar, hata çok açık;  requirements.txt içine cv2 yazmışım halbuki
pythonda cv2 adında bir modül yok , requirements.txt içine gelip cv2 yerine
opencv-python yazarsanız sornunuz çözülecektir.
İyi çalışmalar dilerim.

Can İlgu
canilgu.com

fdemir25 <notifications@github.com>, 12 Eki 2020 Pzt, 17:31 tarihinde şunu
yazdı:
